version: '3'
services:
  db:
    image: postgres:14
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: employment_exchange